#!/bin/sh

PYODIDE_DOCKER_PORT=${PYODIDE_DOCKER_PORT:-"8000"}
PYODIDE_SYSTEM_PORT=${PYODIDE_SYSTEM_PORT:-"8000"}
PYODIDE_DOCKER_IMAGE=${PYODIDE_DOCKER_IMAGE:-"iodide/pyodide-env:0.16.1"}

exec docker run \
    -p $PYODIDE_SYSTEM_PORT:$PYODIDE_DOCKER_PORT \
    -it --rm \
    -v $PWD:/src \
    -v /home/wasonj/pyodide/robotraconteur_pyodide:/rr_src \
    -v /home/wasonj/pyodide/swig:/swig \
    --user root -e NB_UID=$UID -e NB_GID=$GID \
    ${PYODIDE_DOCKER_IMAGE} \
    /bin/bash
